export enum EnvVars {
  PORT = 'PORT',
  SWAGGER = 'SWAGGER',
  CORS = 'CORS',
  // Postgres
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DB_PORT = 'DB_PORT',
  DB_HOST = 'DB_HOST',
  // Redis
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_DB = 'REDIS_DB',
}
