export enum EnvVars {
  PORT = 'PORT',
  SWAGGER = 'SWAGGER',
  // Redis
  CORS = 'CORS',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_DB = 'REDIS_DB',
  // Core
  NODE_ENV = 'NODE_ENV',
}
